### PR TITLE
add Description field

### PR DESCRIPTION
**Pull request by withlin**
as title
```
db, err := gorm.Open("mysql", "root:000000@(10.200.100.219:4406)/test?charset=utf8&parseTime=True&loc=Local")
	db = db.Set("gorm:table_options", "ENGINE=InnoDB CHARSET=utf8")
	if err != nil {
		log.Fatal(err)
	}

	db.LogMode(true)

	m := New(db, DefaultOptions, []*Migration{
		// create persons table
		{
			ID:          "201608301400",
			Description: "create persons table",
			Migrate: func(tx *gorm.DB) error {
				// it's a good pratice to copy the struct inside the function,
				// so side effects are prevented if the original struct changes during the time
				type Person struct {
					gorm.Model
					Name string
				}
				return tx.AutoMigrate(&Person{}).Error
			},
			Rollback: func(tx *gorm.DB) error {
				return tx.DropTable("people").Error
			},
		},
		// add age column to persons
		{
			ID:          "201608301415",
			Description: "add age column to person table",
			Migrate: func(tx *gorm.DB) error {
				// when table already exists, it just adds fields as columns
				type Person struct {
					Age int
				}
				return tx.AutoMigrate(&Person{}).Error
			},
			Rollback: func(tx *gorm.DB) error {
				return tx.Table("people").DropColumn("age").Error
			},
		},
		// add pets table
		{
			ID:          "201608301430",
			Description: "add pets table",
			Migrate: func(tx *gorm.DB) error {
				type Pet struct {
					gorm.Model
					Name     string
					PersonID int
				}
				return tx.AutoMigrate(&Pet{}).Error
			},
			Rollback: func(tx *gorm.DB) error {
				return tx.DropTable("pets").Error
			},
		},
	})

	if err = m.Migrate(); err != nil {
		log.Fatalf("Could not migrate: %v", err)
	}
	log.Printf("Migration did run successfully")

```

### CODE REVIEW

**Comment by withlin** [comment]
@andreynering PTAL! tks.

**Comment by andreynering** [comment]
Hi @withlin, and thanks for opening this pull request.

Two comments about this patch:

1) Why do you think it's interesting to save the description in the database? IMHO, it's enough to have the description in the code (as a comment);
2) As is, this is a breaking change, i.e., it'd break the lib for everyone unless they manually add this column.

**Comment by crufter** [comment]
@andreynering I think there is definitely a use case for storing extra information about a migration (in my case it would be a code version tag that caused the migration), not sure if this library is the place for it or one should just store it in a different table manually. Easy enough to do as part of a migration step?

**Comment by andreynering** [comment]
@crufter Yeah, I think it's probably simple enough to have another table with extra info.

Alternatively you could fork this library in order to add additional columns.

Since this would be a breaking change that would cause a lot of pain to existing users, I'm closing this pull request.

**Pull request closed without merging**
